#!/bin/bash

# Enables job control
set -m

# Enables error propagation
set -e

# Run the server and send it to the background
bash /entrypoint.sh couchbase-server &

# Check if couchbase server is up
check_db() {
  curl --silent http://127.0.0.1:8091/pools > /dev/null
  echo $?
}

# Variable used in echo
i=1
# Echo with
log() {
  echo "[$i] [$(date +"%T")] $@"
  i=`expr $i + 1`
}

# Wait until it's ready
until [[ $(check_db) = 0 ]]; do
  >&2 log "Waiting for Couchbase Server to be available ..."
  sleep 1
done

# Setup index and memory quota
log "$(date +"%T") Init cluster ........."
couchbase-cli cluster-init -c 127.0.0.1 --cluster-username Administrator --cluster-password password \
  --cluster-name myCluster --cluster-ramsize 1024 --cluster-index-ramsize 512 --services data,index,query,fts \
  --index-storage-setting default

# Create the buckets
log "$(date +"%T") Create buckets ........."
couchbase-cli bucket-create -c 127.0.0.1 --username Administrator --password password --bucket-type couchbase --bucket-ramsize 250 --bucket bucket1

# Create user
log "$(date +"%T") Create users ........."
couchbase-cli user-manage -c 127.0.0.1:8091 -u Administrator -p password --set --rbac-username sysadmin --rbac-password password \
 --rbac-name "sysadmin" --roles admin --auth-domain local

couchbase-cli user-manage -c 127.0.0.1:8091 -u Administrator -p password --set --rbac-username admin --rbac-password password \
 --rbac-name "admin" --roles bucket_full_access[*] --auth-domain local

# Need to wait until query service is ready to process N1QL queries
log "$(date +"%T") Waiting for query service ........."
sleep 20

# Create bucket1 indexes
echo "$(date +"%T") Create bucket1 indexes ........."
cbq -u Administrator -p password -s "CREATE PRIMARY INDEX idx_primary ON \`bucket1\`;"
cbq -u Administrator -p password -s "CREATE INDEX idx_type ON \`bucket1\`(_type);"
cbq -u Administrator -p password -s "CREATE INDEX idx_account_id ON \`bucket1\`(id) WHERE (_type = \"account\");"

echo "$(date +"%T") Inserting data ........."

cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ae\", { \"id\": \"ae\", \"density\": 114});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"af\", { \"id\": \"af\", \"density\": 56});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ad\", { \"id\": \"ad\", \"density\": 164});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ag\", { \"id\": \"ag\", \"density\": 234});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ai\", { \"id\": \"ai\", \"density\": 167});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"al\", { \"id\": \"al\", \"density\": 107});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"am\", { \"id\": \"am\", \"density\": 103});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ao\", { \"id\": \"ao\", \"density\": 25});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ar\", { \"id\": \"ar\", \"density\": 16});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"as\", { \"id\": \"as\", \"density\": 278});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"at\", { \"id\": \"at\", \"density\": 106});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"au\", { \"id\": \"au\", \"density\": 3});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"aw\", { \"id\": \"aw\", \"density\": 587});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"az\", { \"id\": \"az\", \"density\": 120});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ba\", { \"id\": \"ba\", \"density\": 69});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"bb\", { \"id\": \"bb\", \"density\": 666});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"bd\", { \"id\": \"bd\", \"density\": 1278});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"be\", { \"id\": \"be\", \"density\": 380});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"bf\", { \"id\": \"bf\", \"density\": 72});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"bg\", { \"id\": \"bg\", \"density\": 65});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"bh\", { \"id\": \"bh\", \"density\": 2062});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"bi\", { \"id\": \"bi\", \"density\": 437});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"bj\", { \"id\": \"bj\", \"density\": 102});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"bm\", { \"id\": \"bm\", \"density\": 1221});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"bn\", { \"id\": \"bn\", \"density\": 82});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"bo\", { \"id\": \"bo\", \"density\": 10});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"br\", { \"id\": \"br\", \"density\": 25});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"bs\", { \"id\": \"bs\", \"density\": 40});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"bt\", { \"id\": \"bt\", \"density\": 21});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"bw\", { \"id\": \"bw\", \"density\": 4});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"by\", { \"id\": \"by\", \"density\": 47});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"bz\", { \"id\": \"bz\", \"density\": 17});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ca\", { \"id\": \"ca\", \"density\": 4});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"cf\", { \"id\": \"cf\", \"density\": 8});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ch\", { \"id\": \"ch\", \"density\": 216});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ci\", { \"id\": \"ci\", \"density\": 78});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ck\", { \"id\": \"ck\", \"density\": 73});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"cl\", { \"id\": \"cl\", \"density\": 24});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"cm\", { \"id\": \"cm\", \"density\": 52});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"cn\", { \"id\": \"cn\", \"density\": 151});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"co\", { \"id\": \"co\", \"density\": 45});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"cr\", { \"id\": \"cr\", \"density\": 97});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"cs\", { \"id\": \"cs\", \"density\": 100});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"cu\", { \"id\": \"cu\", \"density\": 108});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"cv\", { \"id\": \"cv\", \"density\": 137});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"cy\", { \"id\": \"cy\", \"density\": 129});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"cz\", { \"id\": \"cz\", \"density\": 138});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"de\", { \"id\": \"de\", \"density\": 236});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"dj\", { \"id\": \"dj\", \"density\": 42});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"dk\", { \"id\": \"dk\", \"density\": 136});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"dm\", { \"id\": \"dm\", \"density\": 99});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"do\", { \"id\": \"do\", \"density\": 225});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"dz\", { \"id\": \"dz\", \"density\": 18});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ec\", { \"id\": \"ec\", \"density\": 68});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ee\", { \"id\": \"ee\", \"density\": 31});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"eg\", { \"id\": \"eg\", \"density\": 100});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"eh\", { \"id\": \"eh\", \"density\": 2});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"er\", { \"id\": \"er\", \"density\": 51});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"es\", { \"id\": \"es\", \"density\": 93});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"et\", { \"id\": \"et\", \"density\": 108});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"fi\", { \"id\": \"fi\", \"density\": 18});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"fj\", { \"id\": \"fj\", \"density\": 50});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"fk\", { \"id\": \"fk\", \"density\": 0});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"fm\", { \"id\": \"fm\", \"density\": 152});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"fo\", { \"id\": \"fo\", \"density\": 35});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"fr\", { \"id\": \"fr\", \"density\": 119});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ga\", { \"id\": \"ga\", \"density\": 8});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"gb\", { \"id\": \"gb\", \"density\": 275});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"gd\", { \"id\": \"gd\", \"density\": 319});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ge\", { \"id\": \"ge\", \"density\": 56});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"gf\", { \"id\": \"gf\", \"density\": 4});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"gh\", { \"id\": \"gh\", \"density\": 129});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"gi\", { \"id\": \"gi\", \"density\": 3473});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"gl\", { \"id\": \"gl\", \"density\": 0});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"gm\", { \"id\": \"gm\", \"density\": 214});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"gn\", { \"id\": \"gn\", \"density\": 53});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"gp\", { \"id\": \"gp\", \"density\": 266});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"gq\", { \"id\": \"gq\", \"density\": 47});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"gr\", { \"id\": \"gr\", \"density\": 86});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"gt\", { \"id\": \"gt\", \"density\": 161});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"gu\", { \"id\": \"gu\", \"density\": 307});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"gw\", { \"id\": \"gw\", \"density\": 68});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"gy\", { \"id\": \"gy\", \"density\": 4});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"hk\", { \"id\": \"hk\", \"density\": 7075});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"hm\", { \"id\": \"hm\", \"density\": 2003});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"hn\", { \"id\": \"hn\", \"density\": 84});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"hr\", { \"id\": \"hr\", \"density\": 74});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ht\", { \"id\": \"ht\", \"density\": 403});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"hu\", { \"id\": \"hu\", \"density\": 107});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"id\", { \"id\": \"id\", \"density\": 147});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ie\", { \"id\": \"ie\", \"density\": 70});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"il\", { \"id\": \"il\", \"density\": 391});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"in\", { \"id\": \"in\", \"density\": 455});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"io\", { \"id\": \"io\", \"density\": 211});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"iq\", { \"id\": \"iq\", \"density\": 91});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ir\", { \"id\": \"ir\", \"density\": 50});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"is\", { \"id\": \"is\", \"density\": 3});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"it\", { \"id\": \"it\", \"density\": 202});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"jm\", { \"id\": \"jm\", \"density\": 268});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"jo\", { \"id\": \"jo\", \"density\": 112});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"jp\", { \"id\": \"jp\", \"density\": 349});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ke\", { \"id\": \"ke\", \"density\": 90});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"kg\", { \"id\": \"kg\", \"density\": 32});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"kh\", { \"id\": \"kh\", \"density\": 92});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ki\", { \"id\": \"ki\", \"density\": 146});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"km\", { \"id\": \"km\", \"density\": 447});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"kn\", { \"id\": \"kn\", \"density\": 215});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"kw\", { \"id\": \"kw\", \"density\": 236});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ky\", { \"id\": \"ky\", \"density\": 260});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"kz\", { \"id\": \"kz\", \"density\": 7});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"la\", { \"id\": \"la\", \"density\": 30});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"lb\", { \"id\": \"lb\", \"density\": 596});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"lc\", { \"id\": \"lc\", \"density\": 295});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"li\", { \"id\": \"li\", \"density\": 238});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"lk\", { \"id\": \"lk\", \"density\": 334});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"lr\", { \"id\": \"lr\", \"density\": 50});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ls\", { \"id\": \"ls\", \"density\": 75});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"lt\", { \"id\": \"lt\", \"density\": 46});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"lu\", { \"id\": \"lu\", \"density\": 228});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"lv\", { \"id\": \"lv\", \"density\": 31});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ly\", { \"id\": \"ly\", \"density\": 4});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ma\", { \"id\": \"ma\", \"density\": 81});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"mc\", { \"id\": \"mc\", \"density\": 26105});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"md\", { \"id\": \"md\", \"density\": 123});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"mg\", { \"id\": \"mg\", \"density\": 45});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"mh\", { \"id\": \"mh\", \"density\": 295});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ml\", { \"id\": \"ml\", \"density\": 16});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"mm\", { \"id\": \"mm\", \"density\": 82});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"mn\", { \"id\": \"mn\", \"density\": 2});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"mo\", { \"id\": \"mo\", \"density\": 21081});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"mp\", { \"id\": \"mp\", \"density\": 120});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"mq\", { \"id\": \"mq\", \"density\": 363});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"mr\", { \"id\": \"mr\", \"density\": 4});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ms\", { \"id\": \"ms\", \"density\": 52});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"mt\", { \"id\": \"mt\", \"density\": 1350});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"mu\", { \"id\": \"mu\", \"density\": 625});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"mv\", { \"id\": \"mv\", \"density\": 1481});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"mw\", { \"id\": \"mw\", \"density\": 203});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"mx\", { \"id\": \"mx\", \"density\": 67});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"my\", { \"id\": \"my\", \"density\": 98});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"mz\", { \"id\": \"mz\", \"density\": 39});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"na\", { \"id\": \"na\", \"density\": 3});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"nc\", { \"id\": \"nc\", \"density\": 15});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ne\", { \"id\": \"ne\", \"density\": 18});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ng\", { \"id\": \"ng\", \"density\": 215});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ni\", { \"id\": \"ni\", \"density\": 52});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"nl\", { \"id\": \"nl\", \"density\": 507});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"no\", { \"id\": \"no\", \"density\": 15});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"np\", { \"id\": \"np\", \"density\": 207});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"nr\", { \"id\": \"nr\", \"density\": 566});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"nu\", { \"id\": \"nu\", \"density\": 6});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"nz\", { \"id\": \"nz\", \"density\": 18});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"om\", { \"id\": \"om\", \"density\": 16});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"pa\", { \"id\": \"pa\", \"density\": 56});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"pe\", { \"id\": \"pe\", \"density\": 25});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"pf\", { \"id\": \"pf\", \"density\": 78});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"pg\", { \"id\": \"pg\", \"density\": 19});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ph\", { \"id\": \"ph\", \"density\": 357});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"pk\", { \"id\": \"pk\", \"density\": 260});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"pl\", { \"id\": \"pl\", \"density\": 124});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"pm\", { \"id\": \"pm\", \"density\": 28});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"pr\", { \"id\": \"pr\", \"density\": 413});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"pt\", { \"id\": \"pt\", \"density\": 112});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"pw\", { \"id\": \"pw\", \"density\": 48});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"py\", { \"id\": \"py\", \"density\": 17});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"qa\", { \"id\": \"qa\", \"density\": 232});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"re\", { \"id\": \"re\", \"density\": 353});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ro\", { \"id\": \"ro\", \"density\": 85});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ru\", { \"id\": \"ru\", \"density\": 9});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"rw\", { \"id\": \"rw\", \"density\": 507});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"sa\", { \"id\": \"sa\", \"density\": 16});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"sb\", { \"id\": \"sb\", \"density\": 22});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"sc\", { \"id\": \"sc\", \"density\": 207});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"sd\", { \"id\": \"sd\", \"density\": 24});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"se\", { \"id\": \"se\", \"density\": 24});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"sg\", { \"id\": \"sg\", \"density\": 8274});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"sh\", { \"id\": \"sh\", \"density\": 10});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"si\", { \"id\": \"si\", \"density\": 103});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"sk\", { \"id\": \"sk\", \"density\": 113});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"sl\", { \"id\": \"sl\", \"density\": 107});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"sm\", { \"id\": \"sm\", \"density\": 559});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"sn\", { \"id\": \"sn\", \"density\": 85});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"so\", { \"id\": \"so\", \"density\": 24});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"sr\", { \"id\": \"sr\", \"density\": 4});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"st\", { \"id\": \"st\", \"density\": 218});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"sv\", { \"id\": \"sv\", \"density\": 309});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"sy\", { \"id\": \"sy\", \"density\": 100});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"sz\", { \"id\": \"sz\", \"density\": 81});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"tc\", { \"id\": \"tc\", \"density\": 38});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"td\", { \"id\": \"td\", \"density\": 12});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"tg\", { \"id\": \"tg\", \"density\": 147});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"th\", { \"id\": \"th\", \"density\": 135});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"tj\", { \"id\": \"tj\", \"density\": 65});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"tk\", { \"id\": \"tk\", \"density\": 132});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"tl\", { \"id\": \"tl\", \"density\": 89});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"tm\", { \"id\": \"tm\", \"density\": 12});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"tn\", { \"id\": \"tn\", \"density\": 75});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"to\", { \"id\": \"to\", \"density\": 151});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"tr\", { \"id\": \"tr\", \"density\": 106});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"tt\", { \"id\": \"tt\", \"density\": 268});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"tv\", { \"id\": \"tv\", \"density\": 376});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"tw\", { \"id\": \"tw\", \"density\": 669});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ua\", { \"id\": \"ua\", \"density\": 76});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ug\", { \"id\": \"ug\", \"density\": 222});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"us\", { \"id\": \"us\", \"density\": 36});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"uy\", { \"id\": \"uy\", \"density\": 20});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"uz\", { \"id\": \"uz\", \"density\": 76});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ve\", { \"id\": \"ve\", \"density\": 37});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"vi\", { \"id\": \"vi\", \"density\": 300});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"vn\", { \"id\": \"vn\", \"density\": 311});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"vu\", { \"id\": \"vu\", \"density\": 23});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"wf\", { \"id\": \"wf\", \"density\": 83});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ws\", { \"id\": \"ws\", \"density\": 70});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"ye\", { \"id\": \"ye\", \"density\": 55});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"yt\", { \"id\": \"yt\", \"density\": 692});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"za\", { \"id\": \"za\", \"density\": 47});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"zm\", { \"id\": \"zm\", \"density\": 24});"
cbq -u Administrator -p password -s "INSERT INTO bucket1 (KEY, VALUE) VALUES (\"zw\", { \"id\": \"zw\", \"density\": 44});"

echo "$(date +"%T") Data in database!"


fg 1